apiVersion: 1
datasources:
  - name: ADP-Postgres
    type: postgres
    access: proxy
    url: db:5432
    user: adp
    jsonData:
      database: adp
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: adp
